Workflow fix

diff --git a/.github/workflows/commentary_separation.yml b/.github/workflows/commentary_separation.yml
--- a/.github/workflows/commentary_separation.yml
+++ b/.github/workflows/commentary_separation.yml
@@ -6,7 +6,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -18,13 +17,19 @@ jobs:
       with:
         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
         fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
-        branch: master
     - uses: actions/checkout@master
       with:
         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
         fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
         repository: ashtadhyayi-com/data
         branch: master
+        path: ashtadhyayi-com-data
+    - uses: actions/checkout@master
+      with:
+        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+        fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
+        branch: master
+        path: master
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v1
       with:
@@ -34,18 +39,19 @@ jobs:
         python -m pip install --upgrade pip
         python -m pip install git+https://github.com/sanskrit-coders/doc_curation/@master -U
         python -m pip install git+https://github.com/ashtadhyayi/data_curation@master -U
-#    - name: Create local changes
-#      run: |
-#        python -c "from ashtadhyayi_data.reader.ashtadhyayi_com import transformer; transformer.transform(indir=\"`pwd`\", outdir=\"`pwd`/processed_data/\", dry_run=False)"
-#    - name: Commit files
-#      run: |
-#        git config --local user.email "action@github.com"
-#        git config --local user.name "GitHub Action"
-#        git add --all
-#        git commit -m "Add changes" -a
-#    - name: Push changes
-#      uses: ad-m/github-push-action@master
-#      with:
-#        github_token: ${{ secrets.GITHUB_TOKEN }}
-#        branch: processed_data
-#        force: true
+    - name: Create local changes
+      env:
+        TRANSFORM_REPO_TOKEN: ${{ secrets.VISH_TOKEN }}
+        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        cp -rnf change_details master
+        python -c "from ashtadhyayi_data.reader.ashtadhyayi_com import transformer; transformer.transform(indir=\"`pwd`/ashtadhyayi-com-data/\", outdir=\"`pwd`/master\", dry_run=False)"
+    - name: Commit files
+      run: |
+        cd master
+        git config --global user.email "action@github.com"
+        git config --global user.name "GitHub Action"
+        git add --all
+        git diff-index --quiet HEAD || git commit -m "Add changes" -a
+        remote_repo="https://${GITHUB_ACTOR}:${TRANSFORM_REPO_TOKEN}@github.com/sanskrit/ashtadhyayi_com_transforms.git"
+        git push "${remote_repo}" HEAD:master|| (cd .. && git pull --rebase && git commit --allow-empty -m "Dummy commit to trigger workflow rerun upon 'push race condition'." && git push "https://${GITHUB_ACTOR}:${TRANSFORM_REPO_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:trigger_branch)
